000 (98848.000.000) 04/30 20:44:25 Job submitted from host: <132.236.91.36:46278>
...
001 (98848.000.000) 04/30 20:44:25 Job executing on host: <10.1.255.231:46278>
...
006 (98848.000.000) 04/30 20:44:34 Image size of job updated: 1
	3  -  MemoryUsage of job (MB)
	2220  -  ResidentSetSize of job (KB)
...
006 (98848.000.000) 04/30 20:49:35 Image size of job updated: 7859672
	7251  -  MemoryUsage of job (MB)
	7424740  -  ResidentSetSize of job (KB)
...
005 (98848.000.000) 04/30 21:12:07 Job terminated.
	(1) Normal termination (return value 0)
		Usr 0 00:27:33, Sys 0 00:00:05  -  Run Remote Usage
		Usr 0 00:00:00, Sys 0 00:00:00  -  Run Local Usage
		Usr 0 00:27:33, Sys 0 00:00:05  -  Total Remote Usage
		Usr 0 00:00:00, Sys 0 00:00:00  -  Total Local Usage
	0  -  Run Bytes Sent By Job
	0  -  Run Bytes Received By Job
	0  -  Total Bytes Sent By Job
	0  -  Total Bytes Received By Job
	Partitionable Resources :    Usage  Request          
	   Cpus                 :                 1          
	   Disk (KB)            :        1        1          
	   Memory (MB)          :     7251     7251          
...
