000 (98850.000.000) 04/30 20:45:56 Job submitted from host: <132.236.91.36:46278>
...
001 (98850.000.000) 04/30 20:45:58 Job executing on host: <10.1.255.231:46278>
...
006 (98850.000.000) 04/30 20:46:07 Image size of job updated: 1219384
	415  -  MemoryUsage of job (MB)
	424900  -  ResidentSetSize of job (KB)
...
006 (98850.000.000) 04/30 20:51:08 Image size of job updated: 8394112
	7421  -  MemoryUsage of job (MB)
	7598352  -  ResidentSetSize of job (KB)
...
006 (98850.000.000) 04/30 20:56:08 Image size of job updated: 8403772
	7421  -  MemoryUsage of job (MB)
	7598352  -  ResidentSetSize of job (KB)
...
005 (98850.000.000) 04/30 21:06:57 Job terminated.
	(1) Normal termination (return value 0)
		Usr 0 00:27:47, Sys 0 00:00:06  -  Run Remote Usage
		Usr 0 00:00:00, Sys 0 00:00:00  -  Run Local Usage
		Usr 0 00:27:47, Sys 0 00:00:06  -  Total Remote Usage
		Usr 0 00:00:00, Sys 0 00:00:00  -  Total Local Usage
	0  -  Run Bytes Sent By Job
	0  -  Run Bytes Received By Job
	0  -  Total Bytes Sent By Job
	0  -  Total Bytes Received By Job
	Partitionable Resources :    Usage  Request          
	   Cpus                 :                 2          
	   Disk (KB)            :        1        1          
	   Memory (MB)          :     7421     7421          
...
