000 (98832.000.000) 04/30 20:30:16 Job submitted from host: <132.236.91.36:46278>
...
001 (98832.000.000) 04/30 20:30:27 Job executing on host: <10.1.255.231:46278>
...
006 (98832.000.000) 04/30 20:30:36 Image size of job updated: 1219508
	434  -  MemoryUsage of job (MB)
	443548  -  ResidentSetSize of job (KB)
...
005 (98832.000.000) 04/30 20:30:38 Job terminated.
	(1) Normal termination (return value 1)
		Usr 0 00:00:09, Sys 0 00:00:00  -  Run Remote Usage
		Usr 0 00:00:00, Sys 0 00:00:00  -  Run Local Usage
		Usr 0 00:00:09, Sys 0 00:00:00  -  Total Remote Usage
		Usr 0 00:00:00, Sys 0 00:00:00  -  Total Local Usage
	0  -  Run Bytes Sent By Job
	0  -  Run Bytes Received By Job
	0  -  Total Bytes Sent By Job
	0  -  Total Bytes Received By Job
	Partitionable Resources :    Usage  Request          
	   Cpus                 :                 2          
	   Disk (KB)            :        1        1          
	   Memory (MB)          :      434      434          
...
