000 (98851.000.000) 04/30 20:46:07 Job submitted from host: <132.236.91.36:46278>
...
001 (98851.000.000) 04/30 20:46:18 Job executing on host: <10.1.255.231:46278>
...
006 (98851.000.000) 04/30 20:46:27 Image size of job updated: 2189672
	554  -  MemoryUsage of job (MB)
	566892  -  ResidentSetSize of job (KB)
...
006 (98851.000.000) 04/30 20:51:28 Image size of job updated: 9466344
	7659  -  MemoryUsage of job (MB)
	7842744  -  ResidentSetSize of job (KB)
...
006 (98851.000.000) 04/30 20:56:28 Image size of job updated: 9467440
	7659  -  MemoryUsage of job (MB)
	7842744  -  ResidentSetSize of job (KB)
...
005 (98851.000.000) 04/30 21:01:21 Job terminated.
	(1) Normal termination (return value 0)
		Usr 0 00:27:27, Sys 0 00:00:06  -  Run Remote Usage
		Usr 0 00:00:00, Sys 0 00:00:00  -  Run Local Usage
		Usr 0 00:27:27, Sys 0 00:00:06  -  Total Remote Usage
		Usr 0 00:00:00, Sys 0 00:00:00  -  Total Local Usage
	0  -  Run Bytes Sent By Job
	0  -  Run Bytes Received By Job
	0  -  Total Bytes Sent By Job
	0  -  Total Bytes Received By Job
	Partitionable Resources :    Usage  Request          
	   Cpus                 :                 4          
	   Disk (KB)            :        1        1          
	   Memory (MB)          :     7659     7659          
...
