000 (98834.000.000) 04/30 20:30:32 Job submitted from host: <132.236.91.36:46278>
...
001 (98834.000.000) 04/30 20:30:48 Job executing on host: <10.1.255.230:46278>
...
006 (98834.000.000) 04/30 20:30:56 Image size of job updated: 1
	3  -  MemoryUsage of job (MB)
	2224  -  ResidentSetSize of job (KB)
...
006 (98834.000.000) 04/30 20:30:59 Image size of job updated: 3970476
	1005  -  MemoryUsage of job (MB)
	1028288  -  ResidentSetSize of job (KB)
...
005 (98834.000.000) 04/30 20:30:59 Job terminated.
	(1) Normal termination (return value 1)
		Usr 0 00:00:24, Sys 0 00:00:00  -  Run Remote Usage
		Usr 0 00:00:00, Sys 0 00:00:00  -  Run Local Usage
		Usr 0 00:00:24, Sys 0 00:00:00  -  Total Remote Usage
		Usr 0 00:00:00, Sys 0 00:00:00  -  Total Local Usage
	0  -  Run Bytes Sent By Job
	0  -  Run Bytes Received By Job
	0  -  Total Bytes Sent By Job
	0  -  Total Bytes Received By Job
	Partitionable Resources :    Usage  Request          
	   Cpus                 :                 8          
	   Disk (KB)            :        1        1          
	   Memory (MB)          :     1005     1005          
...
