000 (98852.000.000) 04/30 20:46:15 Job submitted from host: <132.236.91.36:46278>
...
001 (98852.000.000) 04/30 20:46:18 Job executing on host: <10.1.255.230:46278>
...
006 (98852.000.000) 04/30 20:46:27 Image size of job updated: 4530792
	1110  -  MemoryUsage of job (MB)
	1136272  -  ResidentSetSize of job (KB)
...
006 (98852.000.000) 04/30 20:51:28 Image size of job updated: 11715048
	8123  -  MemoryUsage of job (MB)
	8317188  -  ResidentSetSize of job (KB)
...
005 (98852.000.000) 04/30 20:57:04 Job terminated.
	(1) Normal termination (return value 0)
		Usr 0 00:27:12, Sys 0 00:00:05  -  Run Remote Usage
		Usr 0 00:00:00, Sys 0 00:00:00  -  Run Local Usage
		Usr 0 00:27:12, Sys 0 00:00:05  -  Total Remote Usage
		Usr 0 00:00:00, Sys 0 00:00:00  -  Total Local Usage
	0  -  Run Bytes Sent By Job
	0  -  Run Bytes Received By Job
	0  -  Total Bytes Sent By Job
	0  -  Total Bytes Received By Job
	Partitionable Resources :    Usage  Request          
	   Cpus                 :                 8          
	   Disk (KB)            :        1        1          
	   Memory (MB)          :     8123     8123          
...
